name: GitHub Profile Views Counter CI
on:
  # 设置一个基于时间表（Cron）的自动触发器。
  schedule:
    # Cron 表达式 '0 */6 * * *' 的含义：
    # - 分钟 (0): 每小时的第 0 分钟（即整点）。
    # - 小时 (*/6): 每隔 6 小时运行一次（即 00:00, 06:00, 12:00, 18:00 UTC）。
    # - 日 (*): 每天。
    # - 月 (*): 每月。
    # - 星期几 (*): 每周的每一天。
    # 工作流将每隔 6 小时自动运行一次。
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.17.0
      - uses: gayanvoice/github-profile-views-counter-action@3.0.0
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
